### PR TITLE
Differentiate between SDL joy index/instance_id.

### LINKED ISSUE #718: Unhandled Exception / Crash when disconnecting controller
### Expected behavior
Gracefully disconnect

### Actual behavior
Crash/Unhandled exception

### Steps to reproduce the behavior
Sometimes it gracefully disconnects, but occasionally when my bluetooth controller disconnects this crashes.  I can reproduce by taking the batteries out.

This happened once while I was playing, I tried to reproduce using debugger, here is the information I found:

```
Exception thrown at 0x00007FFA0405BF80 (SDL2d.dll) in visualboyadvance-m.exe: 0xC0000005: Access violation reading location 0x0000000000000048.

SDL2d.dll!SDL_JoystickRumble_REAL(_SDL_Joystick * joystick, unsigned short low_frequency_rumble, unsigned short high_frequency_rumble, unsigned int duration_ms) Line 776
	at C:\Users\brian\source\repos\vcpkg\buildtrees\sdl2\src\SDL2-2-76158f9b46.clean\src\joystick\SDL_joystick.c(776)
SDL2d.dll!SDL_JoystickClose_REAL(_SDL_Joystick * joystick) Line 826
	at C:\Users\brian\source\repos\vcpkg\buildtrees\sdl2\src\SDL2-2-76158f9b46.clean\src\joystick\SDL_joystick.c(826)
SDL2d.dll!SDL_JoystickClose(_SDL_Joystick * a) Line 246
	at C:\Users\brian\source\repos\vcpkg\buildtrees\sdl2\src\SDL2-2-76158f9b46.clean\src\dynapi\SDL_dynapi_procs.h(246)
visualboyadvance-m.exe!wxSDLJoy::DisconnectController(unsigned char joy) Line 391
	at C:\Users\brian\source\repos\visualboyadvance-m\src\wx\widgets\sdljoy.cpp(391)
visualboyadvance-m.exe!wxSDLJoy::Poll() Line 144
	at C:\Users\brian\source\repos\visualboyadvance-m\src\wx\widgets\sdljoy.cpp(144)
visualboyadvance-m.exe!MainFrame::PollJoysticks() Line 324
	at C:\Users\brian\source\repos\visualboyadvance-m\src\wx\wxvbam.h(324)
visualboyadvance-m.exe!GameArea::OnIdle(wxIdleEvent & event) Line 1110
	at C:\Users\brian\source\repos\visualboyadvance-m\src\wx\panel.cpp(1110)
[External Code]
visualboyadvance-m.exe!wxvbamApp::OnRun() Line 475
	at C:\Users\brian\source\repos\visualboyadvance-m\src\wx\wxvbam.cpp(475)
[External Code]
visualboyadvance-m.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * __formal, int nCmdShow) Line 32
	at C:\Users\brian\source\repos\visualboyadvance-m\src\wx\wxvbam.cpp(32)
visualboyadvance-m.exe!main(int argc, char * * argv) Line 41
	at C:\Users\brian\source\repos\visualboyadvance-m\src\wx\wxvbam.cpp(41)
[External Code]
```

**Local variables in SDL library:**
image

**DisconnectController(unsigned char joy) Local Variables**
image

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
Playing GBA at the time

### Option details

Video driver (simple, opengl):
opengl

Sound driver (directsound, xaudio, openal, SDL):
directsound

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows, Ubuntu

Version of code (pre-built binary version, or commit ref, or just "master"):
master

If relevant, the joystick you are using and the drivers you are using for it:

I'm using an xbox one controller, connected via bluetooth.

### LINKED ISSUE #726: Input configuration is doubled when 2 controllers are connected
### Expected behavior

1. Connect 2 XInput controllers on Windows
2. Open Input configuration panel
3. Input one button on one controller.
4. Only one input shows up in the input configuration panel

### Actual behavior

The input configuration panel shows 2 input at the same time. In fact, after configuring, both controllers work as input.

### Steps to reproduce the behavior

See above.

### ROM details
N/A

### Option details

Video driver (simple, opengl): opengl

Sound driver (directsound, xaudio, openal, SDL): SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.): Windows
Version of code (pre-built binary version, or commit ref, or just "master"): ToT. The issue does not reproduce in v2.1.4.

Any XInput joystick. I tested with 8bitdo controllers in bluetooth and Xbox One controllers with an Xbox One dongle on 2 different machines.

### Additional info

Since the issue does not reproduce in the latest stable build, I am going to try to bisect the issue.

### PR DESCRIPTION
**Pull request by rkitover**
Hopefully fix various bugs caused by not differentiating between SDL
joystick_index and SDL_JoystickID (the joystick instance id.)

Also increase the poll time from 10ms to 25ms.

- Fix #718.
- Fix #726.

Signed-off-by: Rafael Kitover <rkitover@gmail.com>

### CODE REVIEW

**Comment by rkitover** [comment]
@briansrls @Steelskin can you guys please test this branch?

**Comment by briansrls** [comment]
Hi rkitover, I quickly tested the changes.  I see that the input menu is working a bit better now.  However, I'm still seeing crashes on disconnecting a controller.  Are you seeing the same behavior?

File: src/wx/widgets/wx/sdljoy.h [hunk 1]
```diff
@@ -20,25 +20,27 @@
...
-        operator bool();
+    operator bool();
 
-        std::nullptr_t& operator=(std::nullptr_t&& null_ptr);
+    std::nullptr_t& operator=(std::nullptr_t&& null_ptr);
 };
 
 struct wxSDLJoyState {
     wxSDLJoyDev dev;
+    uint8_t index = 0;
```
Comment (briansrls) [inline src/wx/widgets/wx/sdljoy.h:42]: You should note that the index of the joystick will not remain the same through its lifespan.  For example, if there are two controllers open, and they are assigned index 0 & 1 respectively, and you unplug the controller occupying index 0, the controller that previously sat at index 1 will now sit at index 0 (it shifts down to occupy the lowest index).

Because there is no way for us to track this, we really can't use it in any productive way.

File: src/wx/widgets/sdljoy.cpp [hunk 2]
```diff
@@ -314,24 +310,44 @@ void wxSDLJoy::Poll()
 
 void wxSDLJoy::ConnectController(uint8_t joy)
```
Comment (briansrls) [inline src/wx/widgets/sdljoy.cpp:311]: I suggest renaming joy to joystick_index where appropriate.  This will help us differentiate and spot bugs more easily.  And also we should rename joy to something like SDL_JoystickID joystick_instance_id when it represents the instance_id.

**Comment by rkitover** [comment]
Which controller and what OS? I think I had one, but I tested reconnecting and it seems to work fine for me.

File: src/wx/widgets/wx/sdljoy.h (hunk 1 above)
Comment (briansrls) [reply src/wx/widgets/wx/sdljoy.h:42]: The joystick index should be discarded after the connect event and never touched again.  Only instance_id and player_index should be used thereafter.  

From SDL:
```
"The index passed as an argument refers to the N'th game controller on the system. This index is not 
the value which will identify this controller in future controller events. The joystick's instance id 
(SDL_JoystickID) will be used there instead."
```

I think that **player_index** functions the way that you are expecting index to.

From the SDL developer:
```
"Yes, using player_index for binding is the way to go. When connecting a controller it will be assigned 
the first free player index.

Note that if you disconnect and reconnect only 1 controller it will get same player_index. But if you 
disconnect 2 controllers and reconnect them in reverse order they may swap their player_index."
```

File: src/wx/widgets/sdljoy.cpp [hunk 3]
```diff
@@ -224,13 +222,11 @@ void wxSDLJoy::Poll()
             {
                 auto joy = e.cdevice.which;
```
Comment (briansrls) [inline src/wx/widgets/sdljoy.cpp:223]: This should probably be e.jdevice.which

Comment (briansrls) [reply src/wx/widgets/sdljoy.cpp:223]: Same comment to all other JOYDEVICE enums

File: src/wx/widgets/sdljoy.cpp [hunk 4]
```diff
@@ -314,24 +310,44 @@ void wxSDLJoy::Poll()
...
+
+    if (js_dev) {
+        auto instance = SDL_JoystickInstanceID(js_dev);
+
+        instance_map[instance] = &(joystate[joy]);
+
+        joystate[joy].instance = instance;
     }
+
+    joystate[joy].index = joy;
```
Comment (briansrls) [inline src/wx/widgets/sdljoy.cpp:344]: It looks like this will get executed even in a failure case.  Should this be moved to the slightly earlier if statement?

**Comment by rkitover** [comment]
Works fine for me on both Linux and Windows.

**Comment by briansrls** [comment]
Xbox One controller on Windows, here is the traceback

```
SDL2d.dll!00007fff69cdbf80()
SDL2d.dll!00007fff69cdc0b2()
SDL2d.dll!00007fff69b06034()
visualboyadvance-m.exe!wxSDLJoy::DisconnectController(wxSDLJoyState & state) Line 359
	at C:\Users\brian\source\repos\visualboyadvance-m\src\wx\widgets\sdljoy.cpp(359)
visualboyadvance-m.exe!wxSDLJoy::Poll() Line 137
	at C:\Users\brian\source\repos\visualboyadvance-m\src\wx\widgets\sdljoy.cpp(137)
visualboyadvance-m.exe!MainFrame::PollJoysticks() Line 324
	at C:\Users\brian\source\repos\visualboyadvance-m\src\wx\wxvbam.h(324)
visualboyadvance-m.exe!GameArea::OnIdle(wxIdleEvent & event) Line 1130
	at C:\Users\brian\source\repos\visualboyadvance-m\src\wx\panel.cpp(1130)
[External Code]
visualboyadvance-m.exe!wxvbamApp::OnRun() Line 478
	at C:\Users\brian\source\repos\visualboyadvance-m\src\wx\wxvbam.cpp(478)
[External Code]
visualboyadvance-m.exe!WinMain(HINSTANCE__ * hInstance, HINSTANCE__ * hPrevInstance, char * __formal, int nCmdShow) Line 32
	at C:\Users\brian\source\repos\visualboyadvance-m\src\wx\wxvbam.cpp(32)
visualboyadvance-m.exe!main(int argc, char * * argv) Line 41
	at C:\Users\brian\source\repos\visualboyadvance-m\src\wx\wxvbam.cpp(41)
[External Code]

```

Also, I left some comments on your code mostly regarding joystick index.  It looks like our understanding isn't the same yet.

File: src/wx/widgets/sdljoy.cpp (hunk 3 above)
Comment (rkitover) [reply src/wx/widgets/sdljoy.cpp:223]: Valid point.

File: src/wx/widgets/wx/sdljoy.h (hunk 1 above)
Comment (rkitover) [reply src/wx/widgets/wx/sdljoy.h:42]: This is fine, if joystick 0 is configured by the player, it's their problem which joystick is first in their system. The code will work regardless.

**Comment by briansrls** [comment]
I also noticed this printout spammed in the debug logs -

```
4:57:09 PM: Debug: SDL_JoystickOpen(1) failed: There are 1 joysticks available                                             4:58:16 PM: Debug: SDL_JoystickOpen(1) failed: There are 1 joysticks available                                             4:58:16 PM: Debug: SDL_JoystickOpen(1) failed: There are 1 joysticks available                                             4:58:16 PM: Debug: SDL_JoystickOpen(1) failed: There are 1 joysticks available                                             4:58:16 PM: Debug: SDL_JoystickOpen(1) failed: There are 1 joysticks available                                             4:58:16 PM: Debug: SDL_JoystickOpen(1) failed: There are 1 joysticks available                                             4:58:16 PM: Debug: SDL_JoystickOpen(1) failed: There are 1 joysticks available                                             4:58:16 PM: Debug: SDL_JoystickOpen(1) failed: There are 1 joysticks available                                             4:58:16 PM: Debug: SDL_JoystickOpen(1) failed: There are 1 joysticks available                                             4:58:16 PM: Debug: SDL_JoystickOpen(1) failed: There are 1 joysticks available
```

I remember cleaning up some code that basically spammed connect controller when the panel inits, I have no idea the intention of that code.  It's in ```void MainFrame::SetJoystick()```, can you please check out this code?  ex. why is it calling joy.Add over and over?

**Comment by rkitover** [comment]
You are not testing my code, those are the wrong line numbers.

**Comment by briansrls** [comment]
> You are not testing my code, those are the wrong line numbers.

I think this is an issue in my visual studio, I will try to fix it now and retest.  It's in a weird state where git log shows the correct hash but the IDE shows the wrong code 😥

```
commit f6054df636567ee3c4741f4792ed2fcd60f861f7 (HEAD -> joystick-ids-fix, upstream/joystick-ids-fix)
Author: Rafael Kitover <rkitover@gmail.com>
Date:   Fri Sep 4 22:32:15 2020 +0000

    Differentiate between SDL joy index/instance_id.

    Hopefully fix various bugs caused by not differentiating between SDL
    joystick_index and SDL_JoystickID (the joystick instance id.)

    Also increase the poll time from 10ms to 25ms.

    - Fix #718.
    - Fix #726.

    Signed-off-by: Rafael Kitover <rkitover@gmail.com>
```

Here is the output of "git log"

**Comment by briansrls** [comment]
@rkitover I updated the traceback in my comment after deleting my repo.  The code looks correct when I browse to the file, want me to run a test to confirm?

File: src/wx/widgets/wx/sdljoy.h (hunk 1 above)
Comment (briansrls) [reply src/wx/widgets/wx/sdljoy.h:42]: What do you think will happen in the case of multiple controllers:

Joystick 0, iid 0 and Joystick 1, iid 1 are connected, your map looks like this

joystate[iid 0].index = 0
joystate[iid 1].index = 1

Now, the first player disconnects the controller.

Now, SDL considers iid 1 as index 0.  However, your map considers joystate[iid1].index = 1.  You only update the controller that was disconnected.

**Comment by rkitover** [comment]
Did you recompile it? There is no way that setting a variable could produce that backtrace.

**Comment by briansrls** [comment]
> Did you recompile it? There is no way that setting a variable could produce that backtrace.

Sorry, I should have been more clear.  It's throwing an exception that is unhandled.  The backtrace only shows what line would have been executed next.  Basically, it was either in GameControllerClose or JoystickClose last.  I will figure out which one.

**Comment by rkitover** [comment]
That is not how backtraces work, you are running the wrong executable in the debugger.

File: src/wx/widgets/sdljoy.cpp (hunk 4 above)
Comment (rkitover) [reply src/wx/widgets/sdljoy.cpp:344]: This is intended, the state has to exist even if the device is not connected.

File: src/wx/widgets/sdljoy.cpp (hunk 3 above)
Comment (rkitover) [reply src/wx/widgets/sdljoy.cpp]: Fixed, thank you.

**Comment by briansrls** [comment]
Sorry, give me a bit to try and understand what's happening.  I will post some more details when I am more confident

**Comment by briansrls** [comment]
I don't want to present this incorrectly, but here is what I see in VS.  The callstack is odd in the case of an exception, it shows the incorrect line number (obviously this assignment is not calling SDL libraries).  You can see when I hover the arrow on the left, it says "This is the next statement to execute when this thread returns from the current function".  

I found this issue was reproduceable by repeatedly unplugging and plugging in the controller.

image

File: src/wx/widgets/wx/sdljoy.h (hunk 1 above)
Comment (rkitover) [reply src/wx/widgets/wx/sdljoy.h:42]: Also a valid point, I will fix this.

Comment (briansrls) [reply src/wx/widgets/wx/sdljoy.h:42]: OK, I will test some more after your changes.

**Comment by rkitover** [comment]
Ah thanks, my visual studio seems to be broken right now, I will try some more in linux in a few hours, but now I'm going to take a break.

File: src/wx/widgets/wx/sdljoy.h (hunk 1 above)
Comment (rkitover) [reply src/wx/widgets/wx/sdljoy.h:42]: Fixed.

**Comment by rkitover** [comment]
@Steelskin can you please test if this solves your issue?

**Comment by briansrls** [comment]
Anecdotally I am not able to reproduce any of the issues now (crash/double inputs at configure dialogue), looks good to me.

**Review by briansrls — APPROVED** [review]

**Comment by rkitover** [comment]
I think the crash was from the `SDL_GameControllerGetAttached()` call, so I removed it because I don't really need it anyway.

**Comment by rkitover** [comment]
I'm going to do some testing with the switch pro and gamecube controllers again.

**Comment by Steelskin** [comment]
I am here after the battle but I can confirm that this works now, thank you!

**Comment by rkitover** [comment]
@Steelskin nice, thank you for testing!
