### PR TITLE
Languages

### LINKED ISSUE #483: Two words not translated into Brazilian Portuguese (pt_BR)
### Expected behavior
Putting the translation, the emulator (less a few words, because there is no direct translation) would be translated

### Actual behavior
Only two words are not translated, which are Open (GBA) and Quit
Open=Abrir
Quit=Sair

### Steps to reproduce the behavior
Put the translation in Brazilian Portuguese

Sem título

### PR DESCRIPTION
**Pull request by denisfa**
@rkitover This is a bunch of stuff regarding the translation issues:

9784766 : these were never being translated or appeared on the po files because they were not on any XRC and strings from `cmdevents` are processed by cmake syntax.  So we could not use `_()` for gettext.

0b6bcdc : wxWidgets has some issues when translating internal strings (such as the buttons you would expect to be translated automatically). This is due how there is a difference between user and system locale (easy example on commit message about `pt_BR` and `en_US` on 837a48c).

The two above should fix #483 (I did the `pt_BR` translation entirely, and the user of hungarian localization can use transifex to solve the ones he complains there).

3c2acf9 : new operations regarding save states.

A bit unrelated but discovered while working on this:

a572a6a and 5de33cd : just some work that was missing when using key shortcuts for these options (they would not work before, much like the pause issue we had some time ago).

### CODE REVIEW

File: src/wx/cmdevents.cpp [hunk 1]
```diff
@@ -2783,8 +2872,10 @@ EVT_HANDLER(ApplyPatches, "Apply IPS/UPS/IPF patches if found")
 
 EVT_HANDLER(MMX, "Enable MMX")
 {
+#ifdef MMX
```
Comment (rkitover) [inline src/wx/cmdevents.cpp]: I'm not sure we should bother with this, every CPU for more than like two decades has MMX, we should just remove all references to this, but this can be done later.

File: src/wx/guiinit.cpp [hunk 2]
```diff
@@ -2830,6 +2839,17 @@ bool MainFrame::BindControls()
                 continue;
 	    }
 #endif
+#ifndef MMX
```
Comment (rkitover) [inline src/wx/guiinit.cpp]: See above.

**Comment by rkitover** [comment]
I cleaned up the history and merged it.

**Comment by denisfa** [comment]
@rkitover Thank you! I was playing the free weekend of KCD and completely forgot about this... Sorry!

File: src/wx/cmdevents.cpp (hunk 1 above)
Comment (denisfa) [reply src/wx/cmdevents.cpp]: This is enabled only for x32 builds. Can we enable for all? I believe there should not be any issues with x64, but what about ARM and others? I have no idea.

Comment (rkitover) [reply src/wx/cmdevents.cpp]: Yes x64 definitely has MMX, assuming there is no assembly involved, 32 bit assembly doesn't always work for x64 builds.

**Comment by rkitover** [comment]
Not a problem, that looks like a fun game! I think I might try it.

File: src/wx/cmdevents.cpp (hunk 1 above)
Comment (rkitover) [reply src/wx/cmdevents.cpp]: And if there is assembly involved, it may not be better than what the compiler generates with the appropriate `-march` etc. flags, which we need to revisit at some point.
