### PR TITLE
Remove SDL sound driver

### LINKED ISSUE #709: Choppy Framerate on Windows with SDL sound driver
### Expected behavior
Smoother framerate.  To be clear, I am not sure if issue is actually framerate.  Anecdotally, I see it drop to 58 fps regularly during these micro stutters, and when things are more clear it shows 60.  It may take more analysis to determine the actual issue.

### Actual behavior
Getting micro stutters, demonstrated in video.  The leftmost screen is getting small stutters as I move:
https://streamable.com/pv2544

Leftmost is VBAM 2.14, middle is Retroarch running VBAM core 2.1.3, and right is mGBA.

### Steps to reproduce the behavior
Issue is very consistent, regardless of config.  I have not tried games other than Pokemon.  Factory reset, except bilinear filter disabled (does not make a difference, issue is seen with and without bilinear filter).  I am running on windows, have not tried on linux.  Will try on a VM later.

### ROM details

Which games are affected by the issue (please state if GBA or GB game):
I have tested various pokemon games, third generation (GBA) and also pokemon crystal (GB).  I see this issue present in both.

Which games, if any, are NOT affected by the issue (please state if GBA or GB game):
I have always seen this issue, but I have not tested many games.

Include screenshots of ROM Information (File > ROM Information):
image
Issue happens regardless of ROM

If you are using a BIOS file, please say which one.
N/A

### Option details

Video driver (simple, opengl):
opengl

Sound driver (directsound, xaudio, openal, SDL):
SDL

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows

Version of code (pre-built binary version, or commit ref, or just "master"):
I see this issue with built master, and also with binaries downloaded from releases.

### PR DESCRIPTION
**Pull request by rkitover**
Because of reported framerate issues with the SDL sound driver, remove it and make XAudio2 the default on Windows and OpenAL the default everywhere else.

Rewrite the "sdl" value from users' configs to the new default.

Make OpenAL a mandatory dependency as well.

Fix #709

### CODE REVIEW

File: src/wx/config/internal/option-internal.cpp [hunk 1]
```diff
@@ -722,6 +722,16 @@ int StringToAudioApi(const wxString& config_name, const wxString& input) {
...
     }
 
+    wxString input = input_;
+
+// Rewrite sdl to newer default
+    if (input == "sdl")
+#ifdef __WXMSW__
+        input = "xaudio2";
+#else
+        input = "openall";
```
Comment (Steelskin) [inline src/wx/config/internal/option-internal.cpp:732]: nit: `"openal"` (typo)

File: src/wx/config/internal/option-internal.cpp [hunk 2]
```diff
@@ -722,6 +722,16 @@ int StringToAudioApi(const wxString& config_name, const wxString& input) {
         assert(kStringToAudioApi.size() == kNbAudioApis);
     }
 
+    wxString input = input_;
+
+// Rewrite sdl to newer default
+    if (input == "sdl")
```
Comment (Steelskin) [inline src/wx/config/internal/option-internal.cpp:728]: Please add curly braces, it helps prevent issues down the line.

File: src/wx/config/internal/option-internal.cpp [hunk 3]
```diff
@@ -722,6 +722,16 @@ int StringToAudioApi(const wxString& config_name, const wxString& input) {
         assert(kStringToAudioApi.size() == kNbAudioApis);
     }
 
+    wxString input = input_;
+
+// Rewrite sdl to newer default
```
Comment (Steelskin) [inline src/wx/config/internal/option-internal.cpp:727]: nit: wrong indentation.

**Review by Steelskin — CHANGES_REQUESTED** [review]
Thanks for the fix, just a couple minor nits.
