### PR TITLE
Force a panel update when configuring bilinear.

### LINKED ISSUE #727: Billinear filter does not toggle until you open/close the video plugin menu
### Expected behavior
Bilinear filter should immediately take effect when toggled through the menu.

### Actual behavior
Bilinear filter does not seem to take effect until the video plugin menu opens.  Also, bilinear filter doesn't seem to work with the "Simple" video driver?

### Steps to reproduce the behavior
Toggle bilinear filter.

Video driver (simple, opengl):
opengl

### Build details

Operating System (Windows, Mac, Linux (state distribution), etc.):
Windows

Version of code (pre-built binary version, or commit ref, or just "master"):
master

### PR DESCRIPTION
**Pull request by briansrls**
- Fix #727

### CODE REVIEW

File: src/wx/cmdevents.cpp [hunk 1]
```diff
@@ -2872,6 +2872,11 @@ EVT_HANDLER(wxID_ABOUT, "About...")
 EVT_HANDLER(Bilinear, "Use bilinear filter with 3d renderer")
 {
     GetMenuOptionBool("Bilinear", gopts.bilinear);
+    // Force new panel with new bilinear option
+    if (panel->panel) {
```
Comment (briansrls) [inline src/wx/cmdevents.cpp:2876]: It's not necessary to check if the option has changed, because this code is handling a change event.
