### PR TITLE
Disable mirroring for ROMs > 32MB

### LINKED ISSUE #1046: Cannot play GBA ROM (games) greater than 32 MB
### Expected behavior?

All types of GBA games should work fine

### Actual behavior?

As compare to other emulators, even as compare from VBA 1.8.0 beta 3, it doesn't load ROMS greater then 32 MB.

### Steps to reproduce the problem

1. Visual boy advance does not play GBA ROMS greater than 32 MB.

### Error messages?

No issues on original ROM, but I am facing this issue on some specific games (actually modified ROM) which is greater than 32 MB, big name is "Pokemon Adventure Red Chapter beta 15 + Expansion Fix C" which is not loading only in VBA-M, but I am not facing this issue on another emulators such as mGBA, and even VBA v1.8.0 beta 3.

Screenshot (2)
Screenshot (1)

Video driver (simple, opengl): Intel HD Graphics 530
Sound driver (directsound, xaudio, openal, SDL): Realtek HD Audio
Scale Filter Used?:

### Specifications and Build details

VBA-M: 2.1.5
OS: (include version and OS build number using WinVer if on Windows): Windows 11 and Windows 10 (64 Bit)
If using Linux, specify if using xorg or Wayland:
CPU: Intel Core i5- 6500T
GPU: Intel HD Graphics 530
RAM: 8GB

### Copyright Compliance

- [X] There are no infringing files attached to this bug report.

### PR DESCRIPTION
**Pull request by rkitover**
In doMirroring() do nothing if the ROM size is greater than 32MB. This fixes these ROMs automatically working without disabling mirroring in settings.

Fix #1046

### CODE REVIEW

File: src/gba/Globals.h [hunk 1]
```diff
@@ -118,4 +118,7 @@ extern uint16_t IE;
 extern uint16_t IF;
 extern uint16_t IME;
 
+// Let's try for fewer magic numbers, define them here.
+#define SIZE_32MB 0x2000000
```
Comment (Steelskin) [inline src/gba/Globals.h:122]: Could you add it to `sizes.h` instead?

**Review by Steelskin — APPROVED** [review]
